# Generated by Django 4.0.4 on 2022-04-13 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_image_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Ige',
        ),
    ]
