# Generated by Django 4.0.4 on 2022-04-13 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_image_ige'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ige',
            new_name='Image',
        ),
    ]
