# Generated by Django 4.0.4 on 2022-04-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_ige_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onnx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onnx', models.FileField(upload_to='onnx')),
            ],
        ),
    ]
