# Generated by Django 4.0.4 on 2022-04-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_onnx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recognize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onnx', models.FileField(upload_to='onnx')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Onnx',
        ),
    ]
