# Generated by Django 4.0.4 on 2022-04-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_recognize_delete_image_delete_onnx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recognize',
            name='onnx',
        ),
    ]
